### ISSUE TITLE
iOS platform build error: cannot parse the debug map 

### ISSUE THREAD

**Issue by novakov-alexey-zz** [karandpr/SimpleFileTransfer#1]
Getting an error in CLI `tons run ios` and also in Xcode (if open platform/ios project manually):

```
-1: cannot parse the debug map for '/Users/aa/Library/Developer/Xcode/DerivedData/App-fqjtdbpnnzshfwhktmyzdrgfticm/Build/Products/Debug-iphonesimulator/App.app/App': Is a directory
```

```
GenerateDSYMFile /Users/aa/Library/Developer/Xcode/DerivedData/App-fqjtdbpnnzshfwhktmyzdrgfticm/Build/Products/Debug-iphonesimulator/App.app.dSYM /Users/aa/Library/Developer/Xcode/DerivedData/App-fqjtdbpnnzshfwhktmyzdrgfticm/Build/Products/Debug-iphonesimulator/App.app/App (in target: App)
    cd /Users/aa/dev/git/github/SimpleFileTransfer/App/platforms/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/aa/Library/Developer/Xcode/DerivedData/App-fqjtdbpnnzshfwhktmyzdrgfticm/Build/Products/Debug-iphonesimulator/App.app/App -o /Users/aa/Library/Developer/Xcode/DerivedData/App-fqjtdbpnnzshfwhktmyzdrgfticm/Build/Products/Debug-iphonesimulator/App.app.dSYM
```

**Comment by karandpr** [comment]
Not sure about this error. Can you build against 12.1.2 or lower ?

**Comment by novakov-alexey-zz** [comment]
I believe you mean iOS Deployment Target? I've tried with 12.0 and lower, but the same issue.

**Comment by karandpr** [comment]
Yeah. against 12.x SDK. 
tns-ios version is 5.1.0 right ?

**Comment by novakov-alexey-zz** [comment]
Yes. tns-ios is 5.1.0

I've tried again, but this time without the `Webpack workflow`, which I agreed to apply on my first attempt yesterday. Now, it is getting different error:

```
Project successfully prepared (iOS)
Building project...
Xcode build...
warning: Capabilities for App may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'App')
warning: Stale file '/Users/aa/dev/git/github/SimpleFileTransfer/App/platforms/ios/build/sharedpch/SharedPrecompiledHeaders/2411143693780368502/App-Prefix.pch.gch' is located outside of the allowed root paths.
ld: can't open output file for writing: /Users/aa/dev/git/github/SimpleFileTransfer/App/platforms/ios/build/Debug-iphonesimulator/App.app/App, errno=21 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using new build systemnote: Planning buildnote: Constructing build description
** BUILD FAILED **
```

**Comment by karandpr** [comment]
@novakov-alexey 
which is the same error....
`/Users/aa/dev/git/github/SimpleFileTransfer/App/platforms/ios/build/Debug-iphonesimulator/App.app/App` is a directory...
App.app
Linker is expecting a file and receiving a directory. 

Can you delete the directory and try again ?

**Comment by novakov-alexey-zz** [comment]
@karandpr I tried to remove it, but the `build` command is creating it again and it gets failed.
In fact, I have one more dir in the `app`, so that the longest path is:

/Users/aa/dev/git/github/SimpleFileTransfer/App/platforms/ios/build/Debug-iphonesimulator/App.app/app/app

**Comment by karandpr** [comment]
@novakov-alexey
Can you bump the version on iOS to 5.4 and see if it works ?
I don't have access to a Mac machine right now. 

My initial thoughts :
* Something changed in SDK or build tools.
*  Some plugin has compatibility issues with newer build tools.

**Comment by novakov-alexey-zz** [comment]
@karandpr , unfortunately the same error
```
"tns-ios": {
            "version": "5.4.0"
 },
```

**Comment by karandpr** [comment]
@novakov-alexey 
The only relevant SO thread I found out is this one 
https://stackoverflow.com/questions/44097156/xcode-obj-c-cant-open-output-file-for-writing-errno-21-for-architecture-x86-64
One of the suggestions is to remove arm64 architectures from
Build setting -->Architectures section --> valid Architectures

**Comment by novakov-alexey-zz** [comment]
@karandpr if I remove arm64, it fails somewhere in Python framework 😢 

```
Showing All Messages
PhaseScriptExecution NativeScript\ PreBuild /Users/aa/Library/Developer/Xcode/DerivedData/App-fqjtdbpnnzshfwhktmyzdrgfticm/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/App.build/Script-C97FD7AC1ADE5369004DB2A4.sh (in target: App)
    cd /Users/aa/dev/git/github/SimpleFileTransfer/App/platforms/ios
    /bin/sh -c /Users/aa/Library/Developer/Xcode/DerivedData/App-fqjtdbpnnzshfwhktmyzdrgfticm/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/App.build/Script-C97FD7AC1ADE5369004DB2A4.sh

~/dev/git/github/SimpleFileTransfer/App/platforms/ios/internal/metadata-generator/bin ~/dev/git/github/SimpleFileTransfer/App/platforms/ios
Python version: 2.7.10 (default, Feb 22 2019, 21:17:52) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
Traceback (most recent call last):
  File "./build-step-metadata-generator.py", line 107, in <module>
    for arch in env("ARCHS").split():
  File "./build-step-metadata-generator.py", line 12, in env
    return os.environ[env_name]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'ARCHS'
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by karandpr** [comment]
@novakov-alexey 
Yeah. It doesn't make sense to remove the architecture. Do you have an iPhone on which you can run the app ? >_> . I figured it's only throwing errors for x86 so it's probably an issue for emulators.

**Comment by novakov-alexey-zz** [comment]
@karandpr  yes, I do have an iPhone. Do you suggest Native Script Cloud Build instead of local emulator?

**Comment by karandpr** [comment]
Check if the build runs on phone. Chances are it will work on phone but is throwing an error for emulator.  
You can try NativeScript Cloud build too,. 

As a last resort. 

Create a fresh NativeScript Application
Compile and check if it works
Add a plugin ---> Compile and check if it works. 
Do this for all nativescript plugins

When/If all plugins work , copy the source from this folder to you new application folder.
